export const COUNTRIES = [
  {
    id: 'BOLIVIA',
    name: 'BOLIVIA',
    departments: [
      'Santa Cruz',
      'Cochabamba',
      'La Paz',
      'Tarija',
      'Potosí',
      'Chuquisaca',
      'Oruro',
      'Beni',
      'Pando'
    ]
  },
  {
    id: 'ARGENTINA',
    name: 'ARGENTINA',
    departments: [
      'Buenos Aires',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
      'CABA'
    ]
  },
  {
    id: 'BRASIL',
    name: 'BRASIL',
    departments: [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahía',
      'Ceará',
      'Distrito Federal',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Río de Janeiro',
      'Río Grande del Norte',
      'Río Grande del Sur',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins'
    ]
  },
  {
    id: 'CANADA',
    name: 'CANADÁ',
    departments: [
      'Alberta',
      'Columbia Británica',
      'Manitoba',
      'Nuevo Brunswick',
      'Terranova y Labrador',
      'Nueva Escocia',
      'Ontario',
      'Isla del Príncipe Eduardo',
      'Quebec',
      'Saskatchewan',
      'Territorios del Noroeste',
      'Nunavut',
      'Yukón'
    ]
  },
  {
    id: 'CHILE',
    name: 'CHILE',
    departments: [
      'Arica y Parinacota',
      'Tarapacá',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaíso',
      'Metropolitana de Santiago',
      'O’Higgins',
      'Maule',
      'Ñuble',
      'Biobío',
      'Araucanía',
      'Los Ríos',
      'Los Lagos',
      'Aysén',
      'Magallanes'
    ]
  },
  {
    id: 'COLOMBIA',
    name: 'COLOMBIA',
    departments: [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bogotá D.C.',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés y Providencia',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada'
    ]
  },
  {
    id: 'COSTA_RICA',
    name: 'COSTA RICA',
    departments: [
      'San José',
      'Alajuela',
      'Cartago',
      'Heredia',
      'Guanacaste',
      'Puntarenas',
      'Limón'
    ]
  },
  {
    id: 'CUBA',
    name: 'CUBA',
    departments: [
      'Pinar del Río',
      'Artemisa',
      'La Habana',
      'Mayabeque',
      'Matanzas',
      'Villa Clara',
      'Cienfuegos',
      'Sancti Spíritus',
      'Ciego de Ávila',
      'Camagüey',
      'Las Tunas',
      'Holguín',
      'Granma',
      'Santiago de Cuba',
      'Guantánamo',
      'Isla de la Juventud'
    ]
  },
  {
    id: 'ECUADOR',
    name: 'ECUADOR',
    departments: [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo de los Tsáchilas',
      'Sucumbíos',
      'Tungurahua',
      'Zamora Chinchipe'
    ]
  },
  {
    id: 'EL_SALVADOR',
    name: 'EL SALVADOR',
    departments: [
      'Ahuachapán',
      'Cabañas',
      'Chalatenango',
      'Cuscatlán',
      'La Libertad',
      'La Paz',
      'La Unión',
      'Morazán',
      'San Miguel',
      'San Salvador',
      'San Vicente',
      'Santa Ana',
      'Sonsonate',
      'Usulután'
    ]
  },
  {
    id: 'ESTADOS_UNIDOS',
    name: 'ESTADOS UNIDOS',
    departments: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Carolina del Norte',
      'Carolina del Sur',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Luisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'Nueva Jersey',
      'Nueva York',
      'Nuevo Hampshire',
      'Nuevo México',
      'Ohio',
      'Oklahoma',
      'Oregón',
      'Pensilvania',
      'Rhode Island',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Virginia Occidental',
      'Washington',
      'Wisconsin',
      'Wyoming',
      'Washington D.C.'
    ]
  },
  {
    id: 'GUATEMALA',
    name: 'GUATEMALA',
    departments: [
      'Alta Verapaz',
      'Baja Verapaz',
      'Chimaltenango',
      'Chiquimula',
      'El Progreso',
      'Escuintla',
      'Guatemala',
      'Huehuetenango',
      'Izabal',
      'Jalapa',
      'Jutiapa',
      'Petén',
      'Quetzaltenango',
      'Quiché',
      'Retalhuleu',
      'Sacatepéquez',
      'San Marcos',
      'Santa Rosa',
      'Sololá',
      'Suchitepéquez',
      'Totonicapán',
      'Zacapa'
    ]
  },
  {
    id: 'HONDURAS',
    name: 'HONDURAS',
    departments: [
      'Atlántida',
      'Choluteca',
      'Colón',
      'Comayagua',
      'Copán',
      'Cortés',
      'El Paraíso',
      'Francisco Morazán',
      'Gracias a Dios',
      'Intibucá',
      'Islas de la Bahía',
      'La Paz',
      'Lempira',
      'Ocotepeque',
      'Olancho',
      'Santa Bárbara',
      'Valle',
      'Yoro'
    ]
  },
  {
    id: 'MEXICO',
    name: 'MÉXICO',
    departments: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila',
      'Colima',
      'Ciudad de México',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Estado de México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas'
    ]
  },
  {
    id: 'NICARAGUA',
    name: 'NICARAGUA',
    departments: [
      'Boaco',
      'Carazo',
      'Chinandega',
      'Chontales',
      'Estelí',
      'Granada',
      'Jinotega',
      'León',
      'Madriz',
      'Managua',
      'Masaya',
      'Matagalpa',
      'Nueva Segovia',
      'Rivas',
      'Río San Juan',
      'RAAN',
      'RAAS'
    ]
  },
  {
    id: 'PANAMA',
    name: 'PANAMÁ',
    departments: [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Herrera',
      'Los Santos',
      'Panamá',
      'Veraguas',
      'Panamá Oeste'
    ]
  },
  {
    id: 'PARAGUAY',
    name: 'PARAGUAY',
    departments: [
      'Asunción',
      'Concepción',
      'San Pedro',
      'Cordillera',
      'Guairá',
      'Caaguazú',
      'Caazapá',
      'Itapúa',
      'Misiones',
      'Paraguarí',
      'Alto Paraná',
      'Central',
      'Ñeembucú',
      'Amambay',
      'Canindeyú',
      'Presidente Hayes',
      'Boquerón',
      'Alto Paraguay'
    ]
  },
  {
    id: 'PERU',
    name: 'PERÚ',
    departments: [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali'
    ]
  },
  {
    id: 'REPUBLICA_DOMINICANA',
    name: 'REPÚBLICA DOMINICANA',
    departments: [
      'Azua',
      'Baoruco',
      'Barahona',
      'Dajabón',
      'Distrito Nacional',
      'Duarte',
      'Elías Piña',
      'El Seibo',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'Sánchez Ramírez',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Santiago',
      'Santiago Rodríguez',
      'Valverde'
    ]
  },
  {
    id: 'URUGUAY',
    name: 'URUGUAY',
    departments: [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres'
    ]
  },
  {
    id: 'VENEZUELA',
    name: 'VENEZUELA',
    departments: [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Vargas',
      'Yaracuy',
      'Zulia'
    ]
  },
  {
    id: 'BELICE',
    name: 'BELICE',
    departments: ['Belize', 'Cayo', 'Corozal', 'Orange Walk', 'Stann Creek', 'Toledo']
  },
  {
    id: 'GUYANA',
    name: 'GUYANA',
    departments: ['Barima-Waini', 'Cuyuni-Mazaruni', 'Demerara-Mahaica', 'East Berbice-Corentyne', 'Essequibo Islands-West Demerara', 'Mahaica-Berbice', 'Pomeroon-Supenaam', 'Potaro-Siparuni', 'Upper Demerara-Berbice', 'Upper Takutu-Upper Essequibo']
  },
  {
    id: 'SURINAM',
    name: 'SURINAM',
    departments: ['Brokopondo', 'Commewijne', 'Coronie', 'Marowijne', 'Nickerie', 'Para', 'Paramaribo', 'Saramacca', 'Sipaliwini', 'Wanica']
  },
  {
    id: 'HAITI',
    name: 'HAITÍ',
    departments: ['Artibonite', 'Centre', 'Grand\'Anse', 'Nippes', 'Nord', 'Nord-Est', 'Nord-Ouest', 'Ouest', 'Sud', 'Sud-Est']
  },
  {
    id: 'JAMAICA',
    name: 'JAMAICA',
    departments: ['Clarendon', 'Hanover', 'Kingston', 'Manchester', 'Portland', 'Saint Andrew', 'Saint Ann', 'Saint Catherine', 'Saint Elizabeth', 'Saint James', 'Saint Mary', 'Saint Thomas', 'Trelawny', 'Westmoreland']
  },
  {
    id: 'TRINIDAD_Y_TOBAGO',
    name: 'TRINIDAD Y TOBAGO',
    departments: ['Port of Spain', 'San Fernando', 'Arima', 'Chaguanas', 'Point Fortin', 'Couva-Tabaquite-Talparo', 'Diego Martin', 'Penal-Debe', 'Princes Town', 'Rio Claro-Mayaro', 'San Juan-Laventille', 'Sangre Grande', 'Siparia', 'Tunapuna-Piarco', 'Tobago']
  },
  {
    id: 'BAHAMAS',
    name: 'BAHAMAS',
    departments: ['New Providence', 'Grand Bahama', 'Abaco', 'Acklins', 'Andros', 'Berry Islands', 'Bimini', 'Cat Island', 'Crooked Island', 'Eleuthera', 'Exuma', 'Inagua', 'Long Island', 'Mayaguana', 'Ragged Island', 'Rum Cay', 'San Salvador']
  },
  {
    id: 'BARBADOS',
    name: 'BARBADOS',
    departments: ['Christ Church', 'Saint Andrew', 'Saint George', 'Saint James', 'Saint John', 'Saint Joseph', 'Saint Lucy', 'Saint Michael', 'Saint Peter', 'Saint Philip', 'Saint Thomas']
  },
  {
    id: 'SANTA_LUCIA',
    name: 'SANTA LUCÍA',
    departments: ['Anse la Raye', 'Canaries', 'Castries', 'Choiseul', 'Dennery', 'Gros Islet', 'Laborie', 'Micoud', 'Soufrière', 'Vieux Fort']
  },
  {
    id: 'GRANADA',
    name: 'GRANADA',
    departments: ['Saint Andrew', 'Saint David', 'Saint George', 'Saint John', 'Saint Mark', 'Saint Patrick', 'Carriacou and Petite Martinique']
  },
  {
    id: 'DOMINICA',
    name: 'DOMINICA',
    departments: ['Saint Andrew', 'Saint David', 'Saint George', 'Saint John', 'Saint Joseph', 'Saint Luke', 'Saint Mark', 'Saint Patrick', 'Saint Paul', 'Saint Peter']
  },
  {
    id: 'ANTIGUA_Y_BARBUDA',
    name: 'ANTIGUA Y BARBUDA',
    departments: ['Saint George', 'Saint John', 'Saint Mary', 'Saint Paul', 'Saint Peter', 'Saint Philip', 'Barbuda', 'Redonda']
  },
  {
    id: 'SAN_CRISTOBAL_Y_NIEVES',
    name: 'SAN CRISTÓBAL Y NIEVES',
    departments: ['Saint George Basseterre', 'Saint John Capisterre', 'Saint Mary Cayon', 'Saint Paul Capisterre', 'Saint Peter Basseterre', 'Saint Thomas Middle Island', 'Trinity Palmetto Point', 'Christ Church Nichola Town', 'Saint Anne Sandy Point', 'Saint George Gingerland', 'Saint James Windward', 'Saint John Figtree', 'Saint Paul Charlestown', 'Saint Thomas Lowland']
  },
  {
    id: 'SAN_VICENTE_Y_GRANADINAS',
    name: 'SAN VICENTE Y GRANADINAS',
    departments: ['Charlotte', 'Grenadines', 'Saint Andrew', 'Saint David', 'Saint George', 'Saint Patrick']
  }
];

export const getDepartmentsForCountry = (countryId: string) => {
  const country = COUNTRIES.find(c => c.id.toUpperCase() === (countryId || '').toUpperCase());
  return country ? country.departments : [];
};
